#############################################################################
# Makefile for building: VP-Viewer
# Generated by qmake (3.1) (Qt 6.1.0)
# Project:  VP-Viewer.pro
# Template: app
# Command: /home/joaovictor/Qt/6.1.0/gcc_64/bin/qmake -o Makefile VP-Viewer.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../eigen -I../../Qt/6.1.0/gcc_64/include -I../../Qt/6.1.0/gcc_64/include/QtWidgets -I../../Qt/6.1.0/gcc_64/include/QtGui -I../../Qt/6.1.0/gcc_64/include/QtCore -I. -I. -I../../Qt/6.1.0/gcc_64/mkspecs/linux-g++
QMAKE         = /home/joaovictor/Qt/6.1.0/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/joaovictor/Qt/6.1.0/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/joaovictor/Qt/6.1.0/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = VP-Viewer1.0.0
DISTDIR = /home/joaovictor/Code/vptree_jasbick/.tmp/VP-Viewer1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/joaovictor/Qt/6.1.0/gcc_64/lib
LIBS          = $(SUBLIBS) /home/joaovictor/Qt/6.1.0/gcc_64/lib/libQt6Widgets.so /home/joaovictor/Qt/6.1.0/gcc_64/lib/libQt6Gui.so /home/joaovictor/Qt/6.1.0/gcc_64/lib/libQt6Core.so -lpthread -lGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		Histogram/histogram.cpp \
		Histogram/pairwisehistogram.cpp \
		Histogram/pivothistogram.cpp \
		PivotSelection/PivotSelection.cpp qrc_resources.cpp
OBJECTS       = main.o \
		histogram.o \
		pairwisehistogram.o \
		pivothistogram.o \
		PivotSelection.o \
		qrc_resources.o
DIST          = cities.csv \
		names.csv \
		../../Qt/6.1.0/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/common/unix.conf \
		../../Qt/6.1.0/gcc_64/mkspecs/common/linux.conf \
		../../Qt/6.1.0/gcc_64/mkspecs/common/sanitize.conf \
		../../Qt/6.1.0/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt/6.1.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt/6.1.0/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt/6.1.0/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt/6.1.0/gcc_64/mkspecs/qconfig.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_ext_libpng.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_core5compat.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_core5compat_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labsanimation.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labssettings.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_linguist.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_linguist_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3d.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3dparticles.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_shadertools.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_shadertools_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_tools_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/6.1.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/toolchain.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/default_post.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/qt.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/resources_functions.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/resources.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/moc.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/uic.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/qmake_use.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/file_copies.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/yacc.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/lex.prf \
		VP-Viewer.pro Dataset/BasicArrayObject.h \
		Dataset/Dataset-inl.h \
		Dataset/Dataset.h \
		Distance/DistanceFunction.h \
		Distance/EditDistance-inl.h \
		Distance/EditDistance.h \
		Distance/EuclideanDistance-inl.h \
		Distance/EuclideanDistance.h \
		Distance/ManhattanDistance-inl.h \
		Distance/ManhattanDistance.h \
		Distance/BrayCurtisDistance-inl.h \
		Distance/BrayCurtisDistance.h \
		Distance/CanberraDistance-inl.h \
		Distance/CanberraDistance.h \
		Distance/ChebyshevDistance-inl.h \
		Distance/ChebyshevDistance.h \
		Distance/ColorLayoutDistance-inl.h \
		Distance/ColorLayoutDistance.h \
		Distance/DTWDistance-inl.h \
		Distance/DTWDistance.h \
		Distance/JeffreyDivergenceDistance-inl.h \
		Distance/JeffreyDivergenceDistance.h \
		Distance/KullbackLeiblerDivergenceDistance-inl.h \
		Distance/KullbackLeiblerDivergenceDistance.h \
		Distance/MetricHistogramDistance-inl.h \
		Distance/MetricHistogramDistance.h \
		Distance/MorositaDistance-inl.h \
		Distance/MorositaDistance.h \
		Distance/QuiSquareDistance-inl.h \
		Distance/QuiSquareDistance.h \
		Distance/SpearmanDistance-inl.h \
		Distance/SpearmanDistance.h \
		Distance/SquaredChordDistance-inl.h \
		Distance/SquaredChordDistance.h \
		Distance/SumProductDistance-inl.h \
		Distance/SumProductDistance.h \
		Distance/WarpDistance-inl.h \
		Distance/WarpDistance.h \
		Histogram/Histogram.h \
		Histogram/PairwiseHistogram.h \
		Histogram/PivotHistogram.h \
		PivotSelection/PivotSelection.h \
		VpTree/VpTree-inl.h \
		VpTree/VpTree.h \
		VpTree/Node/DirectorNode-inl.h \
		VpTree/Node/DirectorNode.h \
		VpTree/Node/LeafNode-inl.h \
		VpTree/Node/LeafNode.h \
		VpTree/Node/Node-inl.h \
		VpTree/Node/Node.h \
		VpTree/Node/Bucket/Bucket-inl.h \
		VpTree/Node/Bucket/Bucket.h \
		VpTree/Node/Bucket/Pair-inl.h \
		VpTree/Node/Bucket/Pair.h \
		VpTree/View.h \
		VpTree/View-inl.h \
		VpTree/QueueItem.h main.cpp \
		Histogram/histogram.cpp \
		Histogram/pairwisehistogram.cpp \
		Histogram/pivothistogram.cpp \
		PivotSelection/PivotSelection.cpp
QMAKE_TARGET  = VP-Viewer
DESTDIR       = 
TARGET        = VP-Viewer


first: all
####### Build rules

VP-Viewer: ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: VP-Viewer.pro ../../Qt/6.1.0/gcc_64/mkspecs/linux-g++/qmake.conf ../../Qt/6.1.0/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/common/unix.conf \
		../../Qt/6.1.0/gcc_64/mkspecs/common/linux.conf \
		../../Qt/6.1.0/gcc_64/mkspecs/common/sanitize.conf \
		../../Qt/6.1.0/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt/6.1.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt/6.1.0/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt/6.1.0/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt/6.1.0/gcc_64/mkspecs/qconfig.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_ext_libpng.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_core5compat.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_core5compat_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labsanimation.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labssettings.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_linguist.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_linguist_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3d.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3dparticles.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_shadertools.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_shadertools_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_tools_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/6.1.0/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/6.1.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/toolchain.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/default_post.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/qt.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/resources_functions.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/resources.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/moc.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/uic.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/qmake_use.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/file_copies.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/yacc.prf \
		../../Qt/6.1.0/gcc_64/mkspecs/features/lex.prf \
		VP-Viewer.pro \
		resources.qrc \
		../../Qt/6.1.0/gcc_64/lib/libQt6Widgets.prl \
		../../Qt/6.1.0/gcc_64/lib/libQt6Gui.prl \
		../../Qt/6.1.0/gcc_64/lib/libQt6Core.prl
	$(QMAKE) -o Makefile VP-Viewer.pro
../../Qt/6.1.0/gcc_64/mkspecs/features/spec_pre.prf:
../../Qt/6.1.0/gcc_64/mkspecs/common/unix.conf:
../../Qt/6.1.0/gcc_64/mkspecs/common/linux.conf:
../../Qt/6.1.0/gcc_64/mkspecs/common/sanitize.conf:
../../Qt/6.1.0/gcc_64/mkspecs/common/gcc-base.conf:
../../Qt/6.1.0/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../Qt/6.1.0/gcc_64/mkspecs/common/g++-base.conf:
../../Qt/6.1.0/gcc_64/mkspecs/common/g++-unix.conf:
../../Qt/6.1.0/gcc_64/mkspecs/qconfig.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_ext_libpng.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_core5compat.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_core5compat_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labsanimation.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labsanimation_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labssettings.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labssettings_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labssharedimage.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_linguist.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_linguist_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_openglwidgets.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmldom_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3d.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3d_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3diblbaker.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3dparticles.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3dutils.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quicklayouts.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_shadertools.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_shadertools_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_svgwidgets.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_tools_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/6.1.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/6.1.0/gcc_64/mkspecs/features/qt_functions.prf:
../../Qt/6.1.0/gcc_64/mkspecs/features/qt_config.prf:
../../Qt/6.1.0/gcc_64/mkspecs/linux-g++/qmake.conf:
../../Qt/6.1.0/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt/6.1.0/gcc_64/mkspecs/features/exclusive_builds.prf:
../../Qt/6.1.0/gcc_64/mkspecs/features/toolchain.prf:
../../Qt/6.1.0/gcc_64/mkspecs/features/default_pre.prf:
../../Qt/6.1.0/gcc_64/mkspecs/features/resolve_config.prf:
../../Qt/6.1.0/gcc_64/mkspecs/features/default_post.prf:
../../Qt/6.1.0/gcc_64/mkspecs/features/warn_on.prf:
../../Qt/6.1.0/gcc_64/mkspecs/features/qt.prf:
../../Qt/6.1.0/gcc_64/mkspecs/features/resources_functions.prf:
../../Qt/6.1.0/gcc_64/mkspecs/features/resources.prf:
../../Qt/6.1.0/gcc_64/mkspecs/features/moc.prf:
../../Qt/6.1.0/gcc_64/mkspecs/features/unix/opengl.prf:
../../Qt/6.1.0/gcc_64/mkspecs/features/uic.prf:
../../Qt/6.1.0/gcc_64/mkspecs/features/unix/thread.prf:
../../Qt/6.1.0/gcc_64/mkspecs/features/qmake_use.prf:
../../Qt/6.1.0/gcc_64/mkspecs/features/file_copies.prf:
../../Qt/6.1.0/gcc_64/mkspecs/features/testcase_targets.prf:
../../Qt/6.1.0/gcc_64/mkspecs/features/exceptions.prf:
../../Qt/6.1.0/gcc_64/mkspecs/features/yacc.prf:
../../Qt/6.1.0/gcc_64/mkspecs/features/lex.prf:
VP-Viewer.pro:
resources.qrc:
../../Qt/6.1.0/gcc_64/lib/libQt6Widgets.prl:
../../Qt/6.1.0/gcc_64/lib/libQt6Gui.prl:
../../Qt/6.1.0/gcc_64/lib/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile VP-Viewer.pro

qmake_all: FORCE


all: Makefile VP-Viewer

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../Qt/6.1.0/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Dataset/BasicArrayObject.h Dataset/Dataset-inl.h Dataset/Dataset.h Distance/DistanceFunction.h Distance/EditDistance-inl.h Distance/EditDistance.h Distance/EuclideanDistance-inl.h Distance/EuclideanDistance.h Distance/ManhattanDistance-inl.h Distance/ManhattanDistance.h Distance/BrayCurtisDistance-inl.h Distance/BrayCurtisDistance.h Distance/CanberraDistance-inl.h Distance/CanberraDistance.h Distance/ChebyshevDistance-inl.h Distance/ChebyshevDistance.h Distance/ColorLayoutDistance-inl.h Distance/ColorLayoutDistance.h Distance/DTWDistance-inl.h Distance/DTWDistance.h Distance/JeffreyDivergenceDistance-inl.h Distance/JeffreyDivergenceDistance.h Distance/KullbackLeiblerDivergenceDistance-inl.h Distance/KullbackLeiblerDivergenceDistance.h Distance/MetricHistogramDistance-inl.h Distance/MetricHistogramDistance.h Distance/MorositaDistance-inl.h Distance/MorositaDistance.h Distance/QuiSquareDistance-inl.h Distance/QuiSquareDistance.h Distance/SpearmanDistance-inl.h Distance/SpearmanDistance.h Distance/SquaredChordDistance-inl.h Distance/SquaredChordDistance.h Distance/SumProductDistance-inl.h Distance/SumProductDistance.h Distance/WarpDistance-inl.h Distance/WarpDistance.h Histogram/Histogram.h Histogram/PairwiseHistogram.h Histogram/PivotHistogram.h PivotSelection/PivotSelection.h VpTree/VpTree-inl.h VpTree/VpTree.h VpTree/Node/DirectorNode-inl.h VpTree/Node/DirectorNode.h VpTree/Node/LeafNode-inl.h VpTree/Node/LeafNode.h VpTree/Node/Node-inl.h VpTree/Node/Node.h VpTree/Node/Bucket/Bucket-inl.h VpTree/Node/Bucket/Bucket.h VpTree/Node/Bucket/Pair-inl.h VpTree/Node/Bucket/Pair.h VpTree/View.h VpTree/View-inl.h VpTree/QueueItem.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp Histogram/histogram.cpp Histogram/pairwisehistogram.cpp Histogram/pivothistogram.cpp PivotSelection/PivotSelection.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		../../Qt/6.1.0/gcc_64/libexec/rcc \
		lightbreeze.qss \
		folderIcon.png \
		pagefold.qss \
		lightblue.qss
	/home/joaovictor/Qt/6.1.0/gcc_64/libexec/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../Qt/6.1.0/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h ../../Qt/6.1.0/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../../Qt/6.1.0/gcc_64/libexec/uic
	/home/joaovictor/Qt/6.1.0/gcc_64/libexec/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_uic_clean 

####### Compile

main.o: main.cpp Dataset/Dataset.h \
		Dataset/BasicArrayObject.h \
		Dataset/Dataset-inl.h \
		VpTree/VpTree.h \
		VpTree/Node/Node.h \
		VpTree/Node/Node-inl.h \
		VpTree/QueueItem.h \
		VpTree/Node/LeafNode.h \
		VpTree/Node/Bucket/Bucket.h \
		VpTree/Node/Bucket/Pair.h \
		VpTree/Node/Bucket/Pair-inl.h \
		VpTree/Node/Bucket/Bucket-inl.h \
		VpTree/Node/LeafNode-inl.h \
		VpTree/Node/DirectorNode.h \
		Histogram/PivotHistogram.h \
		Histogram/Histogram.h \
		Distance/DistanceFunction.h \
		VpTree/Node/DirectorNode-inl.h \
		PivotSelection/PivotSelection.h \
		eigen/Eigenvalues \
		eigen/Core \
		eigen/src/Core/util/DisableStupidWarnings.h \
		eigen/src/Core/util/Macros.h \
		eigen/src/Core/util/MKL_support.h \
		eigen/src/misc/blas.h \
		eigen/src/Core/util/Constants.h \
		eigen/src/Core/util/Meta.h \
		eigen/src/Core/util/ForwardDeclarations.h \
		eigen/src/Core/util/StaticAssert.h \
		eigen/src/Core/util/XprHelper.h \
		eigen/src/Core/util/Memory.h \
		eigen/src/Core/NumTraits.h \
		eigen/src/Core/MathFunctions.h \
		eigen/src/Core/GenericPacketMath.h \
		eigen/src/Core/MathFunctionsImpl.h \
		eigen/src/Core/arch/Default/ConjHelper.h \
		eigen/src/Core/arch/SSE/PacketMath.h \
		eigen/src/Core/arch/SSE/MathFunctions.h \
		eigen/src/Core/arch/AVX/PacketMath.h \
		eigen/src/Core/arch/AVX/MathFunctions.h \
		eigen/src/Core/arch/AVX512/PacketMath.h \
		eigen/src/Core/arch/AVX512/MathFunctions.h \
		eigen/src/Core/arch/SSE/Complex.h \
		eigen/src/Core/arch/AVX/Complex.h \
		eigen/src/Core/arch/AVX/TypeCasting.h \
		eigen/src/Core/arch/SSE/TypeCasting.h \
		eigen/src/Core/arch/AltiVec/PacketMath.h \
		eigen/src/Core/arch/AltiVec/MathFunctions.h \
		eigen/src/Core/arch/AltiVec/Complex.h \
		eigen/src/Core/arch/NEON/PacketMath.h \
		eigen/src/Core/arch/NEON/MathFunctions.h \
		eigen/src/Core/arch/NEON/Complex.h \
		eigen/src/Core/arch/ZVector/PacketMath.h \
		eigen/src/Core/arch/ZVector/MathFunctions.h \
		eigen/src/Core/arch/ZVector/Complex.h \
		eigen/src/Core/arch/CUDA/Half.h \
		eigen/src/Core/arch/CUDA/PacketMathHalf.h \
		eigen/src/Core/arch/CUDA/TypeCasting.h \
		eigen/src/Core/arch/CUDA/PacketMath.h \
		eigen/src/Core/arch/CUDA/MathFunctions.h \
		eigen/src/Core/arch/Default/Settings.h \
		eigen/src/Core/functors/TernaryFunctors.h \
		eigen/src/Core/functors/BinaryFunctors.h \
		eigen/src/Core/functors/UnaryFunctors.h \
		eigen/src/Core/functors/NullaryFunctors.h \
		eigen/src/Core/functors/StlFunctors.h \
		eigen/src/Core/functors/AssignmentFunctors.h \
		eigen/src/Core/arch/CUDA/Complex.h \
		eigen/src/Core/IO.h \
		eigen/src/Core/DenseCoeffsBase.h \
		eigen/src/Core/DenseBase.h \
		eigen/src/plugins/BlockMethods.h \
		eigen/src/Core/MatrixBase.h \
		eigen/src/plugins/CommonCwiseUnaryOps.h \
		eigen/src/plugins/CommonCwiseBinaryOps.h \
		eigen/src/plugins/MatrixCwiseUnaryOps.h \
		eigen/src/plugins/MatrixCwiseBinaryOps.h \
		eigen/src/Core/EigenBase.h \
		eigen/src/Core/Product.h \
		eigen/src/Core/CoreEvaluators.h \
		eigen/src/Core/AssignEvaluator.h \
		eigen/src/Core/Assign.h \
		eigen/src/Core/ArrayBase.h \
		eigen/src/plugins/ArrayCwiseUnaryOps.h \
		eigen/src/plugins/ArrayCwiseBinaryOps.h \
		eigen/src/Core/util/BlasUtil.h \
		eigen/src/Core/DenseStorage.h \
		eigen/src/Core/NestByValue.h \
		eigen/src/Core/ReturnByValue.h \
		eigen/src/Core/NoAlias.h \
		eigen/src/Core/PlainObjectBase.h \
		eigen/src/Core/Matrix.h \
		eigen/src/Core/Array.h \
		eigen/src/Core/CwiseTernaryOp.h \
		eigen/src/Core/CwiseBinaryOp.h \
		eigen/src/Core/CwiseUnaryOp.h \
		eigen/src/Core/CwiseNullaryOp.h \
		eigen/src/Core/CwiseUnaryView.h \
		eigen/src/Core/SelfCwiseBinaryOp.h \
		eigen/src/Core/Dot.h \
		eigen/src/Core/StableNorm.h \
		eigen/src/Core/Stride.h \
		eigen/src/Core/MapBase.h \
		eigen/src/Core/Map.h \
		eigen/src/Core/Ref.h \
		eigen/src/Core/Block.h \
		eigen/src/Core/VectorBlock.h \
		eigen/src/Core/Transpose.h \
		eigen/src/Core/DiagonalMatrix.h \
		eigen/src/Core/Diagonal.h \
		eigen/src/Core/DiagonalProduct.h \
		eigen/src/Core/Redux.h \
		eigen/src/Core/Visitor.h \
		eigen/src/Core/Fuzzy.h \
		eigen/src/Core/Swap.h \
		eigen/src/Core/CommaInitializer.h \
		eigen/src/Core/GeneralProduct.h \
		eigen/src/Core/Solve.h \
		eigen/src/Core/Inverse.h \
		eigen/src/Core/SolverBase.h \
		eigen/src/Core/PermutationMatrix.h \
		eigen/src/Core/Transpositions.h \
		eigen/src/Core/TriangularMatrix.h \
		eigen/src/Core/SelfAdjointView.h \
		eigen/src/Core/products/GeneralBlockPanelKernel.h \
		eigen/src/Core/products/Parallelizer.h \
		eigen/src/Core/ProductEvaluators.h \
		eigen/src/Core/products/GeneralMatrixVector.h \
		eigen/src/Core/products/GeneralMatrixMatrix.h \
		eigen/src/Core/SolveTriangular.h \
		eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
		eigen/src/Core/products/SelfadjointMatrixVector.h \
		eigen/src/Core/products/SelfadjointMatrixMatrix.h \
		eigen/src/Core/products/SelfadjointProduct.h \
		eigen/src/Core/products/SelfadjointRank2Update.h \
		eigen/src/Core/products/TriangularMatrixVector.h \
		eigen/src/Core/products/TriangularMatrixMatrix.h \
		eigen/src/Core/products/TriangularSolverMatrix.h \
		eigen/src/Core/products/TriangularSolverVector.h \
		eigen/src/Core/BandMatrix.h \
		eigen/src/Core/CoreIterators.h \
		eigen/src/Core/ConditionEstimator.h \
		eigen/src/Core/BooleanRedux.h \
		eigen/src/Core/Select.h \
		eigen/src/Core/VectorwiseOp.h \
		eigen/src/Core/Random.h \
		eigen/src/Core/Replicate.h \
		eigen/src/Core/Reverse.h \
		eigen/src/Core/ArrayWrapper.h \
		eigen/src/Core/products/GeneralMatrixMatrix_BLAS.h \
		eigen/src/Core/products/GeneralMatrixVector_BLAS.h \
		eigen/src/Core/products/GeneralMatrixMatrixTriangular_BLAS.h \
		eigen/src/Core/products/SelfadjointMatrixMatrix_BLAS.h \
		eigen/src/Core/products/SelfadjointMatrixVector_BLAS.h \
		eigen/src/Core/products/TriangularMatrixMatrix_BLAS.h \
		eigen/src/Core/products/TriangularMatrixVector_BLAS.h \
		eigen/src/Core/products/TriangularSolverMatrix_BLAS.h \
		eigen/src/Core/Assign_MKL.h \
		eigen/src/Core/GlobalFunctions.h \
		eigen/src/Core/util/ReenableStupidWarnings.h \
		eigen/Cholesky \
		eigen/Jacobi \
		eigen/src/Jacobi/Jacobi.h \
		eigen/src/Cholesky/LLT.h \
		eigen/src/Cholesky/LDLT.h \
		eigen/src/misc/lapacke.h \
		eigen/src/misc/lapacke_mangling.h \
		eigen/src/Cholesky/LLT_LAPACKE.h \
		eigen/Householder \
		eigen/src/Householder/Householder.h \
		eigen/src/Householder/HouseholderSequence.h \
		eigen/src/Householder/BlockHouseholder.h \
		eigen/LU \
		eigen/src/misc/Kernel.h \
		eigen/src/misc/Image.h \
		eigen/src/LU/FullPivLU.h \
		eigen/src/LU/PartialPivLU.h \
		eigen/src/LU/PartialPivLU_LAPACKE.h \
		eigen/src/LU/Determinant.h \
		eigen/src/LU/InverseImpl.h \
		eigen/src/LU/arch/Inverse_SSE.h \
		eigen/Geometry \
		eigen/SVD \
		eigen/QR \
		eigen/src/QR/HouseholderQR.h \
		eigen/src/QR/FullPivHouseholderQR.h \
		eigen/src/QR/ColPivHouseholderQR.h \
		eigen/src/QR/CompleteOrthogonalDecomposition.h \
		eigen/src/QR/HouseholderQR_LAPACKE.h \
		eigen/src/QR/ColPivHouseholderQR_LAPACKE.h \
		eigen/src/misc/RealSvd2x2.h \
		eigen/src/SVD/UpperBidiagonalization.h \
		eigen/src/SVD/SVDBase.h \
		eigen/src/SVD/JacobiSVD.h \
		eigen/src/SVD/BDCSVD.h \
		eigen/src/SVD/JacobiSVD_LAPACKE.h \
		eigen/src/Geometry/OrthoMethods.h \
		eigen/src/Geometry/EulerAngles.h \
		eigen/src/Geometry/Homogeneous.h \
		eigen/src/Geometry/RotationBase.h \
		eigen/src/Geometry/Rotation2D.h \
		eigen/src/Geometry/Quaternion.h \
		eigen/src/Geometry/AngleAxis.h \
		eigen/src/Geometry/Transform.h \
		eigen/src/Geometry/Translation.h \
		eigen/src/Geometry/Scaling.h \
		eigen/src/Geometry/Hyperplane.h \
		eigen/src/Geometry/ParametrizedLine.h \
		eigen/src/Geometry/AlignedBox.h \
		eigen/src/Geometry/Umeyama.h \
		eigen/src/Geometry/arch/Geometry_SSE.h \
		eigen/src/Eigenvalues/Tridiagonalization.h \
		eigen/src/Eigenvalues/RealSchur.h \
		eigen/src/Eigenvalues/HessenbergDecomposition.h \
		eigen/src/Eigenvalues/EigenSolver.h \
		eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
		eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
		eigen/src/Eigenvalues/ComplexSchur.h \
		eigen/src/Eigenvalues/ComplexEigenSolver.h \
		eigen/src/Eigenvalues/RealQZ.h \
		eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
		eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
		eigen/src/Eigenvalues/RealSchur_LAPACKE.h \
		eigen/src/Eigenvalues/ComplexSchur_LAPACKE.h \
		eigen/src/Eigenvalues/SelfAdjointEigenSolver_LAPACKE.h \
		../../Qt/6.1.0/gcc_64/include/QtWidgets/QProgressBar \
		../../Qt/6.1.0/gcc_64/include/QtWidgets/qprogressbar.h \
		../../Qt/6.1.0/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../Qt/6.1.0/gcc_64/include/QtGui/qtguiglobal.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qglobal.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qconfig.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qtcore-config.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qlogging.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qflags.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qatomic.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qmutex.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qnumeric.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qversiontagging.h \
		../../Qt/6.1.0/gcc_64/include/QtGui/qtgui-config.h \
		../../Qt/6.1.0/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../Qt/6.1.0/gcc_64/include/QtWidgets/qframe.h \
		../../Qt/6.1.0/gcc_64/include/QtWidgets/qwidget.h \
		../../Qt/6.1.0/gcc_64/include/QtGui/qwindowdefs.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qtmetamacros.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/6.1.0/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qobject.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qstring.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qchar.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qstringview.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qpair.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qarraydatapointer.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qarraydataops.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qcontainertools_impl.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qbytearrayview.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qstringliteral.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qstringalgorithms.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qanystringview.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qutf8stringview.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qstringtokenizer.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qlist.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qhashfunctions.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qiterator.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qcompare.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qdatastream.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qiodevicebase.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qiterable.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qmetacontainer.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qcontainerinfo.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qtaggedpointer.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qmath.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qproperty.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qshareddata.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qpropertyprivate.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qmargins.h \
		../../Qt/6.1.0/gcc_64/include/QtGui/qpaintdevice.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qrect.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qsize.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qpoint.h \
		../../Qt/6.1.0/gcc_64/include/QtGui/qpalette.h \
		../../Qt/6.1.0/gcc_64/include/QtGui/qcolor.h \
		../../Qt/6.1.0/gcc_64/include/QtGui/qrgb.h \
		../../Qt/6.1.0/gcc_64/include/QtGui/qrgba64.h \
		../../Qt/6.1.0/gcc_64/include/QtGui/qbrush.h \
		../../Qt/6.1.0/gcc_64/include/QtGui/qimage.h \
		../../Qt/6.1.0/gcc_64/include/QtGui/qpixelformat.h \
		../../Qt/6.1.0/gcc_64/include/QtGui/qtransform.h \
		../../Qt/6.1.0/gcc_64/include/QtGui/qpolygon.h \
		../../Qt/6.1.0/gcc_64/include/QtGui/qregion.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qline.h \
		../../Qt/6.1.0/gcc_64/include/QtGui/qpixmap.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt/6.1.0/gcc_64/include/QtGui/qfont.h \
		../../Qt/6.1.0/gcc_64/include/QtGui/qfontmetrics.h \
		../../Qt/6.1.0/gcc_64/include/QtGui/qfontinfo.h \
		../../Qt/6.1.0/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../Qt/6.1.0/gcc_64/include/QtGui/qcursor.h \
		../../Qt/6.1.0/gcc_64/include/QtGui/qbitmap.h \
		../../Qt/6.1.0/gcc_64/include/QtGui/qkeysequence.h \
		../../Qt/6.1.0/gcc_64/include/QtGui/qevent.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qiodevice.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qpointer.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qurl.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qvariant.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qmap.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qshareddata_impl.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qhash.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qdebug.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qtextstream.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qstringconverter.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qset.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt/6.1.0/gcc_64/include/QtGui/qeventpoint.h \
		../../Qt/6.1.0/gcc_64/include/QtGui/qvector2d.h \
		../../Qt/6.1.0/gcc_64/include/QtGui/qvectornd.h \
		../../Qt/6.1.0/gcc_64/include/QtGui/qpointingdevice.h \
		../../Qt/6.1.0/gcc_64/include/QtGui/qinputdevice.h \
		../../Qt/6.1.0/gcc_64/include/QtGui/qscreen.h \
		../../Qt/6.1.0/gcc_64/include/QtCore/QList \
		../../Qt/6.1.0/gcc_64/include/QtCore/QObject \
		../../Qt/6.1.0/gcc_64/include/QtCore/QRect \
		../../Qt/6.1.0/gcc_64/include/QtCore/QSize \
		../../Qt/6.1.0/gcc_64/include/QtCore/QSizeF \
		../../Qt/6.1.0/gcc_64/include/QtGui/QTransform \
		VpTree/VpTree-inl.h \
		Distance/EuclideanDistance.h \
		Distance/EuclideanDistance-inl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

histogram.o: Histogram/histogram.cpp Histogram/Histogram.h \
		Dataset/Dataset.h \
		Dataset/BasicArrayObject.h \
		Dataset/Dataset-inl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o histogram.o Histogram/histogram.cpp

pairwisehistogram.o: Histogram/pairwisehistogram.cpp Histogram/PairwiseHistogram.h \
		Histogram/Histogram.h \
		Dataset/Dataset.h \
		Dataset/BasicArrayObject.h \
		Dataset/Dataset-inl.h \
		Distance/DistanceFunction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pairwisehistogram.o Histogram/pairwisehistogram.cpp

pivothistogram.o: Histogram/pivothistogram.cpp Histogram/PivotHistogram.h \
		Histogram/Histogram.h \
		Dataset/Dataset.h \
		Dataset/BasicArrayObject.h \
		Dataset/Dataset-inl.h \
		Distance/DistanceFunction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pivothistogram.o Histogram/pivothistogram.cpp

PivotSelection.o: PivotSelection/PivotSelection.cpp PivotSelection/PivotSelection.h \
		Dataset/Dataset.h \
		Dataset/BasicArrayObject.h \
		Dataset/Dataset-inl.h \
		Distance/DistanceFunction.h \
		eigen/Eigenvalues \
		eigen/Core \
		eigen/src/Core/util/DisableStupidWarnings.h \
		eigen/src/Core/util/Macros.h \
		eigen/src/Core/util/MKL_support.h \
		eigen/src/misc/blas.h \
		eigen/src/Core/util/Constants.h \
		eigen/src/Core/util/Meta.h \
		eigen/src/Core/util/ForwardDeclarations.h \
		eigen/src/Core/util/StaticAssert.h \
		eigen/src/Core/util/XprHelper.h \
		eigen/src/Core/util/Memory.h \
		eigen/src/Core/NumTraits.h \
		eigen/src/Core/MathFunctions.h \
		eigen/src/Core/GenericPacketMath.h \
		eigen/src/Core/MathFunctionsImpl.h \
		eigen/src/Core/arch/Default/ConjHelper.h \
		eigen/src/Core/arch/SSE/PacketMath.h \
		eigen/src/Core/arch/SSE/MathFunctions.h \
		eigen/src/Core/arch/AVX/PacketMath.h \
		eigen/src/Core/arch/AVX/MathFunctions.h \
		eigen/src/Core/arch/AVX512/PacketMath.h \
		eigen/src/Core/arch/AVX512/MathFunctions.h \
		eigen/src/Core/arch/SSE/Complex.h \
		eigen/src/Core/arch/AVX/Complex.h \
		eigen/src/Core/arch/AVX/TypeCasting.h \
		eigen/src/Core/arch/SSE/TypeCasting.h \
		eigen/src/Core/arch/AltiVec/PacketMath.h \
		eigen/src/Core/arch/AltiVec/MathFunctions.h \
		eigen/src/Core/arch/AltiVec/Complex.h \
		eigen/src/Core/arch/NEON/PacketMath.h \
		eigen/src/Core/arch/NEON/MathFunctions.h \
		eigen/src/Core/arch/NEON/Complex.h \
		eigen/src/Core/arch/ZVector/PacketMath.h \
		eigen/src/Core/arch/ZVector/MathFunctions.h \
		eigen/src/Core/arch/ZVector/Complex.h \
		eigen/src/Core/arch/CUDA/Half.h \
		eigen/src/Core/arch/CUDA/PacketMathHalf.h \
		eigen/src/Core/arch/CUDA/TypeCasting.h \
		eigen/src/Core/arch/CUDA/PacketMath.h \
		eigen/src/Core/arch/CUDA/MathFunctions.h \
		eigen/src/Core/arch/Default/Settings.h \
		eigen/src/Core/functors/TernaryFunctors.h \
		eigen/src/Core/functors/BinaryFunctors.h \
		eigen/src/Core/functors/UnaryFunctors.h \
		eigen/src/Core/functors/NullaryFunctors.h \
		eigen/src/Core/functors/StlFunctors.h \
		eigen/src/Core/functors/AssignmentFunctors.h \
		eigen/src/Core/arch/CUDA/Complex.h \
		eigen/src/Core/IO.h \
		eigen/src/Core/DenseCoeffsBase.h \
		eigen/src/Core/DenseBase.h \
		eigen/src/plugins/BlockMethods.h \
		eigen/src/Core/MatrixBase.h \
		eigen/src/plugins/CommonCwiseUnaryOps.h \
		eigen/src/plugins/CommonCwiseBinaryOps.h \
		eigen/src/plugins/MatrixCwiseUnaryOps.h \
		eigen/src/plugins/MatrixCwiseBinaryOps.h \
		eigen/src/Core/EigenBase.h \
		eigen/src/Core/Product.h \
		eigen/src/Core/CoreEvaluators.h \
		eigen/src/Core/AssignEvaluator.h \
		eigen/src/Core/Assign.h \
		eigen/src/Core/ArrayBase.h \
		eigen/src/plugins/ArrayCwiseUnaryOps.h \
		eigen/src/plugins/ArrayCwiseBinaryOps.h \
		eigen/src/Core/util/BlasUtil.h \
		eigen/src/Core/DenseStorage.h \
		eigen/src/Core/NestByValue.h \
		eigen/src/Core/ReturnByValue.h \
		eigen/src/Core/NoAlias.h \
		eigen/src/Core/PlainObjectBase.h \
		eigen/src/Core/Matrix.h \
		eigen/src/Core/Array.h \
		eigen/src/Core/CwiseTernaryOp.h \
		eigen/src/Core/CwiseBinaryOp.h \
		eigen/src/Core/CwiseUnaryOp.h \
		eigen/src/Core/CwiseNullaryOp.h \
		eigen/src/Core/CwiseUnaryView.h \
		eigen/src/Core/SelfCwiseBinaryOp.h \
		eigen/src/Core/Dot.h \
		eigen/src/Core/StableNorm.h \
		eigen/src/Core/Stride.h \
		eigen/src/Core/MapBase.h \
		eigen/src/Core/Map.h \
		eigen/src/Core/Ref.h \
		eigen/src/Core/Block.h \
		eigen/src/Core/VectorBlock.h \
		eigen/src/Core/Transpose.h \
		eigen/src/Core/DiagonalMatrix.h \
		eigen/src/Core/Diagonal.h \
		eigen/src/Core/DiagonalProduct.h \
		eigen/src/Core/Redux.h \
		eigen/src/Core/Visitor.h \
		eigen/src/Core/Fuzzy.h \
		eigen/src/Core/Swap.h \
		eigen/src/Core/CommaInitializer.h \
		eigen/src/Core/GeneralProduct.h \
		eigen/src/Core/Solve.h \
		eigen/src/Core/Inverse.h \
		eigen/src/Core/SolverBase.h \
		eigen/src/Core/PermutationMatrix.h \
		eigen/src/Core/Transpositions.h \
		eigen/src/Core/TriangularMatrix.h \
		eigen/src/Core/SelfAdjointView.h \
		eigen/src/Core/products/GeneralBlockPanelKernel.h \
		eigen/src/Core/products/Parallelizer.h \
		eigen/src/Core/ProductEvaluators.h \
		eigen/src/Core/products/GeneralMatrixVector.h \
		eigen/src/Core/products/GeneralMatrixMatrix.h \
		eigen/src/Core/SolveTriangular.h \
		eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
		eigen/src/Core/products/SelfadjointMatrixVector.h \
		eigen/src/Core/products/SelfadjointMatrixMatrix.h \
		eigen/src/Core/products/SelfadjointProduct.h \
		eigen/src/Core/products/SelfadjointRank2Update.h \
		eigen/src/Core/products/TriangularMatrixVector.h \
		eigen/src/Core/products/TriangularMatrixMatrix.h \
		eigen/src/Core/products/TriangularSolverMatrix.h \
		eigen/src/Core/products/TriangularSolverVector.h \
		eigen/src/Core/BandMatrix.h \
		eigen/src/Core/CoreIterators.h \
		eigen/src/Core/ConditionEstimator.h \
		eigen/src/Core/BooleanRedux.h \
		eigen/src/Core/Select.h \
		eigen/src/Core/VectorwiseOp.h \
		eigen/src/Core/Random.h \
		eigen/src/Core/Replicate.h \
		eigen/src/Core/Reverse.h \
		eigen/src/Core/ArrayWrapper.h \
		eigen/src/Core/products/GeneralMatrixMatrix_BLAS.h \
		eigen/src/Core/products/GeneralMatrixVector_BLAS.h \
		eigen/src/Core/products/GeneralMatrixMatrixTriangular_BLAS.h \
		eigen/src/Core/products/SelfadjointMatrixMatrix_BLAS.h \
		eigen/src/Core/products/SelfadjointMatrixVector_BLAS.h \
		eigen/src/Core/products/TriangularMatrixMatrix_BLAS.h \
		eigen/src/Core/products/TriangularMatrixVector_BLAS.h \
		eigen/src/Core/products/TriangularSolverMatrix_BLAS.h \
		eigen/src/Core/Assign_MKL.h \
		eigen/src/Core/GlobalFunctions.h \
		eigen/src/Core/util/ReenableStupidWarnings.h \
		eigen/Cholesky \
		eigen/Jacobi \
		eigen/src/Jacobi/Jacobi.h \
		eigen/src/Cholesky/LLT.h \
		eigen/src/Cholesky/LDLT.h \
		eigen/src/misc/lapacke.h \
		eigen/src/misc/lapacke_mangling.h \
		eigen/src/Cholesky/LLT_LAPACKE.h \
		eigen/Householder \
		eigen/src/Householder/Householder.h \
		eigen/src/Householder/HouseholderSequence.h \
		eigen/src/Householder/BlockHouseholder.h \
		eigen/LU \
		eigen/src/misc/Kernel.h \
		eigen/src/misc/Image.h \
		eigen/src/LU/FullPivLU.h \
		eigen/src/LU/PartialPivLU.h \
		eigen/src/LU/PartialPivLU_LAPACKE.h \
		eigen/src/LU/Determinant.h \
		eigen/src/LU/InverseImpl.h \
		eigen/src/LU/arch/Inverse_SSE.h \
		eigen/Geometry \
		eigen/SVD \
		eigen/QR \
		eigen/src/QR/HouseholderQR.h \
		eigen/src/QR/FullPivHouseholderQR.h \
		eigen/src/QR/ColPivHouseholderQR.h \
		eigen/src/QR/CompleteOrthogonalDecomposition.h \
		eigen/src/QR/HouseholderQR_LAPACKE.h \
		eigen/src/QR/ColPivHouseholderQR_LAPACKE.h \
		eigen/src/misc/RealSvd2x2.h \
		eigen/src/SVD/UpperBidiagonalization.h \
		eigen/src/SVD/SVDBase.h \
		eigen/src/SVD/JacobiSVD.h \
		eigen/src/SVD/BDCSVD.h \
		eigen/src/SVD/JacobiSVD_LAPACKE.h \
		eigen/src/Geometry/OrthoMethods.h \
		eigen/src/Geometry/EulerAngles.h \
		eigen/src/Geometry/Homogeneous.h \
		eigen/src/Geometry/RotationBase.h \
		eigen/src/Geometry/Rotation2D.h \
		eigen/src/Geometry/Quaternion.h \
		eigen/src/Geometry/AngleAxis.h \
		eigen/src/Geometry/Transform.h \
		eigen/src/Geometry/Translation.h \
		eigen/src/Geometry/Scaling.h \
		eigen/src/Geometry/Hyperplane.h \
		eigen/src/Geometry/ParametrizedLine.h \
		eigen/src/Geometry/AlignedBox.h \
		eigen/src/Geometry/Umeyama.h \
		eigen/src/Geometry/arch/Geometry_SSE.h \
		eigen/src/Eigenvalues/Tridiagonalization.h \
		eigen/src/Eigenvalues/RealSchur.h \
		eigen/src/Eigenvalues/HessenbergDecomposition.h \
		eigen/src/Eigenvalues/EigenSolver.h \
		eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
		eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
		eigen/src/Eigenvalues/ComplexSchur.h \
		eigen/src/Eigenvalues/ComplexEigenSolver.h \
		eigen/src/Eigenvalues/RealQZ.h \
		eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
		eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
		eigen/src/Eigenvalues/RealSchur_LAPACKE.h \
		eigen/src/Eigenvalues/ComplexSchur_LAPACKE.h \
		eigen/src/Eigenvalues/SelfAdjointEigenSolver_LAPACKE.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PivotSelection.o PivotSelection/PivotSelection.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

